Repository EntryDSM/Casper-Application, pull requests merged in 2025-05, with the labels that each got.

#6 Test/3 docs snyc test
  .github/workflows/auto-sync-pr-to-docs.yml
  src/main/kotlin/hs/kr/entrydsm/application/CasperApplication.kt
Labels: Test

#8 Fix/7-confict-code-block
  casper-convention/src/main/kotlin/io/casper/convention/model/CodeElement.kt
  casper-convention/src/main/kotlin/io/casper/convention/model/DocumentationProblem.kt
  casper-convention/src/main/kotlin/io/casper/convention/service/DocCheckService.kt
  casper-convention/src/main/kotlin/io/casper/convention/tasks/DocCheckTask.kt
Labels: Fix

#10 Feature/9 pre commit setting
  .pre-commit-config.yaml
  build-check.sh
  check-commit-message.sh
Labels: Setup

#14 Refactor/13 pre commit 재설정
  .gitconfig
  .github/hooks/pre-commit
  .pre-commit-config.yaml
  build-check.sh
  check-commit-message.sh
Labels: Refactor

#16 Refactor/15 pre commit 분리
  .github/hooks/commit-msg
  .github/hooks/pre-commit
Labels: Refactor
